export const FETCH_LATEST_BLOCK = "FETCH_LATEST_BLOCK";
export const SET_LATEST_BLOCK = "SET_LATEST_BLOCK";
export const SET_LATEST_BLOCK_ERROR = "SET_LATEST_BLOCK_ERROR";

export const FETCH_SINGLE_BLOCK = "FETCH_SINGLE_BLOCK";
export const SET_SINGLE_BLOCK = "SET_SINGLE_BLOCK";
export const SET_SINGLE_BLOCK_ERROR = "SET_SINGLE_BLOCK_ERROR";

export const FETCH_SINGLE_TRANSACTION_BLOCK = "FETCH_SINGLE_TRANSACTION_BLOCK";
export const SET_SINGLE_TRANSACTION_BLOCK = "SET_SINGLE_TRANSACTION_BLOCK";
export const SET_SINGLE_TRANSACTION_BLOCK_ERROR =
  "SET_SINGLE_TRANSACTION_BLOCK_ERROR";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
